name: test-twinkle

on: [push]

jobs:
  build:
    name: test-twinkle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install twinkled
        run: cargo install twinkled
      - name: Run Twinkle
        run: nohup twinkled &
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
